name: Auto Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release folder
        run: mkdir -p github-release
        
      - name: 检出代码（包含 submodules）
        uses: actions/checkout@v3
        with:
          submodules: true  # 递归拉取 submodules

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'tar.gz'
          filename: 'github-release/zig-mbedtls.tar.gz'
          exclusions: '*.git* github-release'

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          files: github-release/zig-mbedtls.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
